project:
  type: website
  output-dir: docs
website:
  title: "Jay Lowe's Blog"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/
      - icon: twitter
        href: https://twitter.com
  favicon: logo.png
  twitter-card: true
  site-url: https://example.com
format:
  html:
    theme: materia
    css: styles.css
    include-after-body: ./footer.html


