project:
  type: website
  output-dir: docs
website:
  title: "The ogjaylowe blog"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/
      - icon: twitter
        href: https://twitter.com
format:
  html:
    theme: 
      light: journal
      dark: slate
    css: styles.css



