project:
  type: website
  output-dir: docs
website:
  title: "Jay Lowe's Blog"
  navbar:
    right:
      - about.qmd
  favicon: logo.png
  site-url: https://ogjaylowe.com
format:
  html:
    theme: materia
    css: styles.css
    include-after-body: ./footer.html


